services:
  web:
    build: ./
    ports:
      - "8080:8080"
    networks:
      - db-network
    volumes:
      - ./:/app/
    command: ["yarn", "start"]
    restart: "no"
  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - db-network
    volumes:
      - app:/data/postgres
networks:
  db-network:
volumes:
  app:
